version: '3'
services:
  fdp:
    build: .
    image: ""
    command: fdp-run HOSTNAME 8080 --db http://db:8890/sparql
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "tenforce/virtuoso"
    ports:
        - "8890:8890"
        - "1111:1111"
    environment:
        SPARQL_UPDATE: "true"