version: '3'
services:
  fdp:
    image: "nlesc/fairdatapoint"
    command: fdp-run HOSTNAME 80 --db http://db:8890/sparql
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: "tenforce/virtuoso"
    ports:
        - "8890:8890"
        - "1111:1111"
    environment:
        SPARQL_UPDATE: "true"
    volumes:
        - DATABASE_PATH:/data